# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'swift(NSAttributedString和NSMutableAttributedString)' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'SnapKit'
  # Pods for swift(NSAttributedString和NSMutableAttributedString)

  target 'swift(NSAttributedString和NSMutableAttributedString)Tests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'swift(NSAttributedString和NSMutableAttributedString)UITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
